### ISSUE TITLE
Vectron Fork Modded Textures Rendering Improperly

### ISSUE THREAD

**Issue by Akull9** [daveyliam/mapwriter#40]
I compiled the latest from Vectron's fork of Mapwriter and am experiencing textures improperly loading in the minimap.
This only seems to happen with modded blocks. The ones on the screenshots are from Natura and Steves Factory Manager. I haven't tried it without a resourcepack yet.
![2015-04-14_07 20 46](https://cloud.githubusercontent.com/assets/6075254/7138686/bb2d9628-e276-11e4-8af7-1c507a1dcddf.png)
![2015-04-14_07 20 56](https://cloud.githubusercontent.com/assets/6075254/7138687/bb531f42-e276-11e4-9b2f-1c820d8ed2c2.png)

**Comment by Vectron** [comment]
what minecraft version is this?
and what version of natura and steve factory manager are you using?

**Comment by Akull9** [comment]
Minecraft Version 1.7.10
Steve's Factory Manager Version A93
Natura Version 2.2.0.1

I'm Not sure if the versions of the mods will make a difference...
Using the straight 1.7.10 port by jk-5 I don't seem to have this problem.

**Comment by Vectron** [comment]
i cant seem to reproduce this, i only notice that most machines from steves dont give a texture at all.
have you tried it with the default texture pack?

**Comment by Akull9** [comment]
So I tested it without a resourcepack...
![2015-05-06_18 21 00](https://cloud.githubusercontent.com/assets/6075254/7506940/68e9a37c-f41c-11e4-8d0c-86e4f904ab6a.png)
![2015-05-06_18 21 10](https://cloud.githubusercontent.com/assets/6075254/7506941/68ef3af8-f41c-11e4-8ee4-2973a5eb957f.png)
It seems that modded blocks aren't being rendered at all in the minimap (I placed Furnaces for reference).
I'm thinking the clouds from natura are rendering like that because they're semi-transparent blocks, while the other blocks I don't understand...

Using EnderIO version 1.7.10-2.2.8.367 in these screenshots.

**Comment by Vectron** [comment]
i got this fixed in the latest comit, should work as intended again

**Comment by Akull9** [comment]
Thanks, it works now!
